/**:
  ros__parameters:
    # Camera and projection settings
    camera_frame: "camera_optical_frame"
    fov_x_deg: 90.0
    fov_y_deg: 60.0
    
    # Display settings
    fullscreen: true
    fps: 60
    
    # Eye appearance - ALERT EYES
    eye:
      width_divisor: 3.8  # Medium size, attentive
      aspect_ratio: 1.4  # Slightly tall, wide open
      spacing_divisor: 3
      vertical_position: 0.5
    
    pupil:
      size_divisor: 2.3  # Medium pupil, focused
      aspect_ratio: 1.3
      margin_x: 5  # Wide movement range (scanning)
      margin_y: 5
    
    highlight:
      size_divisor: 5
      offset_x_divisor: 6
      offset_y_divisor: 6
    
    gradient:
      layers: 5
      outer_color: 35
      inner_color: 0
    
    # Eye motion - QUICK AND RESPONSIVE
    motion:
      smoothing_factor: 0.25  # Fast response to changes
    
    # Blink settings - QUICK AND EFFICIENT
    blink:
      enabled: true
      interval_min: 4.0  # Moderate blink rate
      interval_max: 7.0
      duration: 0.13  # Quick, efficient blink
    
    saccade:
      enabled: true
      speed_multiplier: 3.0  # Fast scanning movements
