/**:
  ros__parameters:
    # Eye shape and size
    eye:
      # Eye dimensions (relative to screen size)
      # eye_width_divisor: screen_size is divided by this value
      # Smaller value = larger eyes (e.g., 3 = large, 6 = small)
      width_divisor: 4
      
      # Aspect ratio (height = width * aspect_ratio)
      # 1.0 = circle, 1.2 = slightly tall oval, 1.5 = very tall oval
      aspect_ratio: 1.2
      
      # Spacing between eyes (relative to screen width)
      # Smaller value = eyes closer together
      spacing_divisor: 3
      
      # Vertical position (0.5 = center, 0.3 = upper, 0.7 = lower)
      vertical_position: 0.5
    
    # Pupil (iris) settings
    pupil:
      # Pupil size relative to eye
      # Larger value = smaller pupil (e.g., 1.5 = large, 3 = small)
      size_divisor: 2.0
      
      # Pupil aspect ratio
      aspect_ratio: 1.3
      
      # Movement range margin (pixels from edge)
      # Larger value = more restricted movement
      margin_x: 10
      margin_y: 10
    
    # Highlight (light reflection) settings
    highlight:
      # Size relative to pupil
      size_divisor: 5
      
      # Position offset relative to pupil size
      offset_x_divisor: 6
      offset_y_divisor: 6
    
    # Gradient settings for pupil
    gradient:
      # Number of gradient layers
      layers: 5
      
      # Color gradient (from outer to inner)
      # Values 0-255 for grayscale
      outer_color: 40
      inner_color: 0
