/**:
  ros__parameters:
    # Camera and projection settings
    camera_frame: "camera_optical_frame"
    fov_x_deg: 90.0
    fov_y_deg: 60.0
    
    # Display settings
    fullscreen: true
    fps: 60
    
    # Eye appearance settings - LARGE EYES
    eye:
      width_divisor: 3  # Larger eyes (default: 4)
      aspect_ratio: 1.3
      spacing_divisor: 2.5  # Eyes further apart
      vertical_position: 0.5
    
    pupil:
      size_divisor: 1.8  # Larger pupil (default: 2.0)
      aspect_ratio: 1.4
      margin_x: 15  # More restricted movement
      margin_y: 15
    
    highlight:
      size_divisor: 4  # Larger highlight
      offset_x_divisor: 5
      offset_y_divisor: 5
    
    gradient:
      layers: 7  # More gradient layers for smoother look
      outer_color: 50
      inner_color: 0
    
    # Eye motion settings
    motion:
      smoothing_factor: 0.12  # Slightly smoother for larger eyes
    
    blink:
      enabled: false
    
    saccade:
      enabled: false
